apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  labels:
    name: proxy-service
    component: service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    name: proxy-api
    component: api
